# Generated by Django 5.2.1 on 2025-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(default=1, max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
